<?php
$this->headTitle('Смена пароля');

$this->mainMenu()->setActiveItemId('admin');

$form->get('old_password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Старый пароль'
]);

$form->get('new_password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Новый пароль'
]);

$form->get('confirm_new_password')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Повтор нового пароля'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-outline-success']);

$form->prepare();
?>


<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Измение пароля для <?= $this->escapeHtml($user->getEmail()) ?></h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
      <?= $this->formLabel($form->get('old_password')); ?>
      <?= $this->formElement($form->get('old_password')); ?>
      <?= $this->formElementErrors($form->get('old_password')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('new_password')); ?>
      <?= $this->formElement($form->get('new_password')); ?>
      <?= $this->formElementErrors($form->get('new_password')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('confirm_new_password')); ?>
      <?= $this->formElement($form->get('confirm_new_password')); ?>
      <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>
    <a href="<?= $this->url('users') ?>" class="btn btn-link">Отмена</a>

    <?= $this->form()->closeTag(); ?>
  </div>
</div>   


