<?php
$this->headTitle('Редактирвоание пользователя');

$this->mainMenu()->setActiveItemId('admin');

$form->get('email')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'name@example.com'
]);

$form->get('login')->setAttributes([
  'class' => 'form-control',
  'readonly'  => 'true',
]);

$form->get('full_name')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Грузовичков Петя'
]);

$form->get('status')->setAttributes([
  'class' => 'custom-select'
]);

$form->get('roles')->setAttributes([
  'class' => 'form-control'
]);

$form->get('submit')
  ->setAttributes(['class' => 'btn btn-outline-success'])
  ->setValue('Сохранить');

$form->prepare();
?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Редактирование пользователя <?= $this->escapeHtml($user->getLogin()) ?></h1>
    </div>
  </div>
</div>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
      <?= $this->formLabel($form->get('email')); ?>
      <?= $this->formElement($form->get('email')); ?>
      <?= $this->formElementErrors($form->get('email')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('login')); ?>
      <?= $this->formElement($form->get('login')); ?>
      <?= $this->formElementErrors($form->get('login')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('full_name')); ?>
      <?= $this->formElement($form->get('full_name')); ?>
      <?= $this->formElementErrors($form->get('full_name')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('status')); ?>
      <?= $this->formElement($form->get('status')); ?>
      <?= $this->formElementErrors($form->get('status')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('roles')); ?>
      <?= $this->formElement($form->get('roles')); ?>
      <?= $this->formElementErrors($form->get('roles')); ?>
    </div>

    <?= $this->formElement($form->get('submit')); ?>
    <a href="<?= $this->url('users') ?>" class="btn btn-link">Отмена</a>

    <?= $this->form()->closeTag(); ?>
  </div>
</div>   

