<?php
$this->headTitle('Пользователи');

$this->mainMenu()->setActiveItemId('admin');

?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Пользователи ONLINE</h1>
    </div>
  </div>
</div>

<table class="table table-striped">
  <tr>
    <th>Пользователь</th>
    <th>Доступ</th>
    <th>Дата последней активности</th>
  </tr>
  <?php foreach ($onlineUser as $user) { ?>
  <tr>
    <td><?php echo $userList[$user->getUser()]->getFullName(); ?></td>
    <td>
      <?php echo $userList[$user->getUser()]->getRolesAsString(); ?>
    </td>
    <td><?php echo date('H:i:s d.m.Y', $user->getValue()) ?></td>
  </tr>
  <?php } ?>
</table>