<?php
$this->headTitle('Просмотр пользователя');

$this->mainMenu()->setActiveItemId('admin');
?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Просмотр <?= $this->escapeHtml($user->getEmail()) ?></h1>
    </div>
  </div>
</div>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
  <a class="btn btn-outline-secondary" href="<?= $this->url('users'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span>
  </a>
  <a class="btn btn-outline-warning" href="<?= $this->url('users',
    ['action' => 'edit', 'id' => $user->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil"></span> Редактировать
  </a>
  <a class="btn btn-outline-danger" href="<?= $this->url('users',
    ['action' => 'change-password', 'id' => $user->getId()]); ?>">
    <span class="glyphicon glyphicon-asterisk"></span> Сменить пароль
  </a>
</p>

<div class="row">
  <div class="col-md-6">
    <table class="table table-striped table-bordered">
      <tr>
        <th>ID:</th>
        <td>
        <?= $this->escapeHtml($user->getId()) ?></th>
      </tr>
      <tr>
        <th>E-mail:</th>
        <td>
        <?= $this->escapeHtml($user->getEmail()) ?></th>
      </tr>
      <tr>
        <th>Логин:</th>
        <td>
        <?= $this->escapeHtml($user->getLogin()) ?></th>
      </tr>
      <tr>
        <th>Имя:</th>
        <td>
        <?= $this->escapeHtml($user->getFullName()) ?></th>
      </tr>
      <tr>
        <th>Дата создания:</th>
        <td>
        <?= $this->escapeHtml($user->getDateCreated()) ?></th>
      </tr>
      <tr>
        <th>Статус:</th>
        <td>
        <?= $this->escapeHtml($user->getStatusAsString()) ?></th>
      </tr>
      <tr>
        <th>Роль:</th>
        <td>
        <?= $this->escapeHtml($user->getRolesAsString()) ?></th>
      </tr>
    </table>
  </div>
</div>