<?= $this->doctype() ?>

<html lang="en">
<head>
  <meta charset="utf-8">
    <?= $this->headTitle('Регистрация')->setSeparator(' :: '); ?>

  <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('css/bootstrap-light.min.css'))
    ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
  ?>

  <!-- Scripts -->
  <?= $this->headScript()
    ->prependFile($this->basePath('js/jquery-ui.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
  ?>

  <style>
    .page-header {
      margin-top: 60px;
    }
  </style>
</head>
<body>
<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
  <div class="container">
    <a href="/" class="navbar-brand">
      PROXY-service
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navigation bar -->
    <?php
    // Check if the activeMenuItemId passed to layout view model
    // and if so, use it for setting active navbar item.
    if (isset($activeMenuItemId)) {
      $this->mainMenu()->setActiveItemId($activeMenuItemId);
    }

    // Render the navbar
    echo $this->mainMenu()->render();
    ?>
  </div>
</div>

<div class="container">
      <!-- Page content placeholder -->
      <?= $this->content; ?>
  <hr>
  <footer>
    <p>&copy; <?= '2018 - '. date('Y') ?> Greenway</p>
  </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
