<?php if ($this->pageCount) { ?>
<div class="text-center col-12">
  <ul class="pagination">
    <?php if (isset($this->previous)) { ?>
    <li class="page-item">
      <a class="page-link" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query' => ['page' => $this->previous, 'search' => $this->search, 'device' => $this->device]]) ?>">&laquo;</a>
    </li>
    <?php } else { ?>
    <li class="page-item disabled">
      <a class="page-link" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query' => ['page' => $this->previous, 'search' => $this->search, 'device' => $this->device]]) ?>">&laquo;</a>
    </li>
    <?php } ?>

    <?php foreach ($this->pagesInRange as $page) { ?>
      <?php if ($page != $this->current) { ?>
    <li class="page-item">
      <a class="page-link" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query'=>['page'=>$page, 'search' => $this->search, 'device' => $this->device]]); ?>"><?php echo $this->escapeHtml($page); ?></a>
    </li>
      <?php } else { ?>
    <li class="page-item active">
      <a class="page-link" href="#" onclick="return false;"><?php echo $this->escapeHtml($page); ?></a>
    </li>
      <?php } ?>
    <?php } ?>

    <?php if (isset($this->next)) { ?>
      <li class="page-item">
        <a class="page-link" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query' => ['page' => $this->next, 'search' => $this->search, 'device' => $this->device]]) ?>">&raquo;</a>
      </li>
    <?php } else { ?>
      <li class="page-item disabled">
        <a class="page-link" href="<?php echo $this->url($this->route, ['action' => $this->action], ['query' => ['page' => $this->next, 'search' => $this->search, 'device' => $this->device]]) ?>">&raquo;</a>
      </li>
    <?php } ?>
  </ul>
</div>
<?php }