<?php
$this->headTitle('Редактирование роли');

$this->mainMenu()->setActiveItemId('admin');

$form->get('name')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Наименование роли'
]);

$form->get('description')->setAttributes([
  'class' => 'form-control',
  'placeholder' => 'Описание'
]);

$form->get('parent')->setAttributes([
  'class' => 'form-control',
]);


$form->get('submit')
  ->setAttributes(['class' => 'btn btn-outline-success'])
  ->setValue('Сохранить');

$form->prepare();
?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Редактирование роли</h1>
    </div>
  </div>
</div>

<p>
  <a class="btn btn-outline-secondary" href="#" onclick="history.back();">
    <span class="glyphicon glyphicon-arrow-left"></span>
  </a>
  <a class="btn btn-outline-warning"
     href="<?= $this->url('roles', ['action' => 'editPermissions', 'id' => $role->getId()]) ?>">
    <span class="glyphicon glyphicon-check"></span> Редактирование доступа
  </a>
</p>

<div class="row">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
      <?= $this->formLabel($form->get('name')); ?>
      <?= $this->formElement($form->get('name')); ?>
      <?= $this->formElementErrors($form->get('name')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('description')); ?>
      <?= $this->formElement($form->get('description')); ?>
      <?= $this->formElementErrors($form->get('description')); ?>
    </div>

    <div class="form-group">
      <?= $this->formLabel($form->get('parent')); ?>
      <?= $this->formElement($form->get('parent')); ?>
      <?= $this->formElementErrors($form->get('parent')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>
    <a href="<?= $this->url('roles') ?>" class="btn btn-link">Отмена</a>

    <?= $this->form()->closeTag(); ?>
  </div>
</div>   

