<?php
$this->headTitle('Редактирование разрешений');

$this->mainMenu()->setActiveItemId('admin');

$form->get('submit')
  ->setAttributes(['class' => 'btn btn-outline-success'])
  ->setValue('Сохранить');

$form->prepare();
?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h3>Редактирование разрешений для <?= $this->escapeHtml($role->getName()) ?></h3>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <?= $this->form()->openTag($form); ?>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Наименование</th>
        <th>Описание</th>
      </tr>
      <?php foreach ($allPermissions as $permission):
        $element = $form->get('permissions')->get($permission->getName());
        ?>
        <tr>
          <td>
            <div class="checkbox">
              <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                            value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                  <?php if ($element->isChecked()) echo 'checked' ?>
                  <?php if ($element->getAttribute('disabled')) echo 'disabled' ?>>
                <?= $this->escapeHtml($element->getLabel()) ?>
              </label>
              <?= $this->formElementErrors($element); ?>
            </div>
          </td>
          <td>
            <?= $this->escapeHtml($permission->getDescription()) ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </table>
    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>
    <a href="<?= $this->url('roles', ['action' => 'view', 'id' => $role->getId()]) ?>" class="btn btn-link">Отмена</a>

    <?= $this->form()->closeTag(); ?>
  </div>
</div>

<div class="row">
  <div class="col-md-6">


  </div>
</div>   

