<?php
$this->headTitle('Просмотр роли');

$this->mainMenu()->setActiveItemId('admin');

?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>View Role</h1>
    </div>
  </div>
</div>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
  <a class="btn btn-outline-secondary" href="<?= $this->url('roles'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span>
  </a>
  <a class="btn btn-outline-warning" href="<?= $this->url('roles',
    ['action' => 'edit', 'id' => $role->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil"></span> Изменить
  </a>
</p>

<div class="row">
  <div class="col-md-8">
    <table class="table table-striped table-bordered">
      <tr>
        <th>ID:</th>
        <td>
        <?= $this->escapeHtml($role->getId()) ?></th>
      </tr>
      <tr>
        <th>Наименование:</th>
        <td>
        <?= $this->escapeHtml($role->getName()) ?></th>
      </tr>
      <tr>
        <th>Описание:</th>
        <td>
        <?= $this->escapeHtml($role->getDescription()) ?></th>
      </tr>
      <tr>
        <th>Дата создания:</th>
        <td>
        <?= $this->escapeHtml($role->getDateCreated()) ?></th>
      </tr>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-8 col-md-7 col-sm-6">
    <h2>Разрешения</h2>
  </div>
</div>

<p>
  <a class="btn btn-outline-warning" href="<?= $this->url('roles', ['action' => 'editPermissions', 'id' => $role->getId()]) ?>">
    <span class="glyphicon glyphicon-check"></span> Изменить
  </a>
</p>

<div class="row">
  <div class="col-md-8">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Разрешение</th>
        <th>Описание</th>
      </tr>
      <?php foreach ($allPermissions as $permission): ?>
        <tr>
          <td class="form-group">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
              <label class="custom-control-label"> <?= $this->escapeHtml($permission->getName()) ?> </label>
            <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()] == 'inherited') { ?>
              <em>(унаследован)</em>
            <?php } ?>
            </div>
          </td>
          <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
        </tr>
      <?php endforeach; ?>
    </table>
  </div>
</div>
