<?php
$this->headTitle('Просмотр разрешения');

$this->mainMenu()->setActiveItemId('admin');

?>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h1>Просмотр разрешения</h1>
    </div>
  </div>
</div>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
  <a class="btn btn-outline-secondary" href="<?= $this->url('permissions'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span>
  </a>
  <a class="btn btn-outline-warning" href="<?= $this->url('permissions',
    ['action' => 'edit', 'id' => $permission->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil"></span> Редактировать
  </a>
  <a class="btn btn-outline-danger" href="<?= $this->url('permissions',
    ['action' => 'delete', 'id' => $permission->getId()]); ?>"
    onclick="if(confirm('Вы действительно хотите удалить разрешение?')) { return true; } else { return false; }">
      <span class="glyphicon glyphicon-remove"></span> Удалить
  </a>
</p>

<div class="row">
  <div class="col-md-6">
    <table class="table table-striped table-bordered">
      <tr>
        <th>ID:</th>
        <td>
        <?= $this->escapeHtml($permission->getId()) ?></th>
      </tr>
      <tr>
        <th>Наименование:</th>
        <td>
        <?= $this->escapeHtml($permission->getName()) ?></th>
      </tr>
      <tr>
        <th>Описание:</th>
        <td>
        <?= $this->escapeHtml($permission->getDescription()) ?></th>
      </tr>
      <tr>
        <th>Дата создания:</th>
        <td>
        <?= $this->escapeHtml($permission->getDateCreated()) ?></th>
      </tr>
    </table>
  </div>
</div>