<?php
$this->headTitle('Главная');

$this->mainMenu()->setActiveItemId('home');

?>
<div class="page-header">
  <div class="row">
    <div class="col-12">
      <h2>
      </h2>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    loadStat();
  });

  function loadStat() {
    $.post(
      '/stat',
      {},
      function (response) {
        $('#stat').html(response);

        let timer = setTimeout(loadStat, 60000);
      },
      'html'
    );
  }
</script>
<script src="/js/amcharts4/core.js"></script>
<script src="/js/amcharts4/charts.js"></script>
<script src="/js/amcharts4/themes/animated.js"></script>
<div id="stat">
  <div class="row">
    <div class="col-12 align-content-center">
      Загрузка данных...
    </div>
  </div>
</div>
