<?php
$this->headTitle('Метрики');

$this->mainMenu()->setActiveItemId('metrika');

?>

<script src="/js/amcharts4/core.js"></script>
<script src="/js/amcharts4/charts.js"></script>
<script src="/js/amcharts4/themes/animated.js"></script>

<div class="page-header">
  <div class="row">
    <div class="col-lg-8 col-md-7 col-sm-6">
      <h2>Метрики</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <form method="post">
      <div class="row">
        <div class="col-2">
          <input type="text" size="10" id="date" name="date" value="<?php echo $date ?>" class="form-control" readonly/>
        </div>
        <div class="col-1">
          <button type="submit" class="btn btn-outline-success">
            Показать
          </button>
        </div>
      </div>
    </form>

    <script type="text/javascript">
      $(function () {
        $('#date').datepicker({
          dateFormat:       'yy-mm-dd',
          showButtonPanel:  true,
          maxDate:          "+0d"
        });
      });

    </script>
  </div>
</div>
<br/>
<?php if(isset($date) && '' !== $date) { ?>
<div class="row">
  <div class="col-12">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Динамика запросов
      </div>
      <div class="card-body">
        <div class="card-text">
          <script>
            am4core.ready(function() {

              //am4core.useTheme(am4themes_animated);

              let chart = am4core.create("chartdiv", am4charts.XYChart);

              chart.data = [<?php echo implode(',', $result['stat']) ?>];

              chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mi:ss";

              var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
              var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

              var series = chart.series.push(new am4charts.LineSeries());
              series.dataFields.valueY = "value";
              series.dataFields.dateX = "date";
              series.tooltipText = "{value}";
              series.strokeWidth = 2;
              series.minBulletDistance = 15;

              series.tooltip.background.cornerRadius = 20;
              series.tooltip.background.strokeOpacity = 0;
              series.tooltip.pointerOrientation = "vertical";
              series.tooltip.label.minWidth = 40;
              series.tooltip.label.minHeight = 40;
              series.tooltip.label.textAlign = "middle";
              series.tooltip.label.textValign = "middle";

              var bullet = series.bullets.push(new am4charts.CircleBullet());
              bullet.circle.strokeWidth = 2;
              bullet.circle.radius = 4;
              bullet.circle.fill = am4core.color("#fff");

              var bullethover = bullet.states.create("hover");
              bullethover.properties.scale = 1.3;

              chart.cursor = new am4charts.XYCursor();
              chart.cursor.behavior = "panXY";
              chart.cursor.xAxis = dateAxis;
              chart.cursor.snapToSeries = series;

              // Create a horizontal scrollbar with previe and place it underneath the date axis
              chart.scrollbarX = new am4charts.XYChartScrollbar();
              chart.scrollbarX.series.push(series);
              chart.scrollbarX.parent = chart.bottomAxesContainer;

              chart.events.on("ready", function () {
                dateAxis.zoom({start:0.79, end:1});
              });

            });
          </script>
          <div id="chartdiv" style="height: 400px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Динамика скорости сервера
      </div>
      <div class="card-body">
        <div class="card-text">
          <script>
            am4core.ready(function() {

              //am4core.useTheme(am4themes_animated);

              let chart = am4core.create("chartdiv2", am4charts.XYChart);

              chart.data = [<?php echo implode(',', $result['stat2']) ?>];

              chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mi:ss";

              var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
              var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

              var series = chart.series.push(new am4charts.LineSeries());
              series.dataFields.valueY = "value";
              series.dataFields.dateX = "date";
              series.tooltipText = "{value}";
              series.strokeWidth = 2;
              series.minBulletDistance = 15;

              series.tooltip.background.cornerRadius = 20;
              series.tooltip.background.strokeOpacity = 0;
              series.tooltip.pointerOrientation = "vertical";
              series.tooltip.label.minWidth = 40;
              series.tooltip.label.minHeight = 40;
              series.tooltip.label.textAlign = "middle";
              series.tooltip.label.textValign = "middle";

              var bullet = series.bullets.push(new am4charts.CircleBullet());
              bullet.circle.strokeWidth = 2;
              bullet.circle.radius = 4;
              bullet.circle.fill = am4core.color("#fff");

              var bullethover = bullet.states.create("hover");
              bullethover.properties.scale = 1.3;

              chart.cursor = new am4charts.XYCursor();
              chart.cursor.behavior = "panXY";
              chart.cursor.xAxis = dateAxis;
              chart.cursor.snapToSeries = series;

              // Create a horizontal scrollbar with previe and place it underneath the date axis
              chart.scrollbarX = new am4charts.XYChartScrollbar();
              chart.scrollbarX.series.push(series);
              chart.scrollbarX.parent = chart.bottomAxesContainer;

              chart.events.on("ready", function () {
                dateAxis.zoom({start:0.79, end:1});
              });

            });
          </script>
          <div id="chartdiv2" style="height: 400px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php } ?>