<div class="row">
  <div class="col-3">
    <div class="card text-white <?php if ('online' == $result['proxyMode']) echo 'bg-success'; if ('proxy' == $result['proxyMode']) echo 'bg-warning'; if ('offline' == $result['proxyMode']) echo 'bg-danger'; ?> mb-3">
      <div class="card-header">
        Proxy сервис
      </div>
      <div class="card-body">
        <h4 class="card-title"><?php echo mb_strtoupper($result['proxyMode']); ?></h4>
        <?php if ('offline' == $result['proxyMode']) { echo date('d.m.Y H:i:s', $result['offlineModeTime']); } ?>&nbsp;
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="card text-white <?php if ('online' == $result['serverStatus']) echo 'bg-success'; if ('offline' == $result['serverStatus']) echo 'bg-danger'; ?> mb-3">
      <div class="card-header">
        Сервер билетов
      </div>
      <div class="card-body">
        <h4 class="card-title"><?php echo mb_strtoupper($result['serverStatus']); ?></h4>
        &nbsp;
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Скорость запросов
      </div>
      <div class="card-body">
        <h4 class="card-title"><?php echo $result['speedRequest']; ?> з/м</h4>
        &nbsp;
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Скорость сервера
      </div>
      <div class="card-body">
        <h4 class="card-title"><?php echo $result['speedServer'] ?> б/с</h4>
        &nbsp;
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Динамика запросов
      </div>
      <div class="card-body">
        <div class="card-text">
          <script>
            am4core.ready(function() {

              //am4core.useTheme(am4themes_animated);

              let chart = am4core.create("chartdiv", am4charts.XYChart);

              chart.data = [<?php echo implode(',', $result['stat']) ?>];

              chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mi:ss";

              var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
              var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

              var series = chart.series.push(new am4charts.LineSeries());
              series.dataFields.valueY = "value";
              series.dataFields.dateX = "date";
              series.tooltipText = "{value}";
              series.strokeWidth = 2;
              series.minBulletDistance = 15;

              series.tooltip.background.cornerRadius = 20;
              series.tooltip.background.strokeOpacity = 0;
              series.tooltip.pointerOrientation = "vertical";
              series.tooltip.label.minWidth = 40;
              series.tooltip.label.minHeight = 40;
              series.tooltip.label.textAlign = "middle";
              series.tooltip.label.textValign = "middle";

              var bullet = series.bullets.push(new am4charts.CircleBullet());
              bullet.circle.strokeWidth = 2;
              bullet.circle.radius = 4;
              bullet.circle.fill = am4core.color("#fff");

              var bullethover = bullet.states.create("hover");
              bullethover.properties.scale = 1.3;

              chart.cursor = new am4charts.XYCursor();
              chart.cursor.behavior = "panXY";
              chart.cursor.xAxis = dateAxis;
              chart.cursor.snapToSeries = series;

              chart.events.on("ready", function () {

              });

            });
          </script>
          <div id="chartdiv" style="height: 200px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card border-secondary mb-3">
      <div class="card-header">
        Динамика скорости сервера
      </div>
      <div class="card-body">
        <div class="card-text">
          <script>
            am4core.ready(function() {

              //am4core.useTheme(am4themes_animated);

              let chart = am4core.create("chartdiv2", am4charts.XYChart);

              chart.data = [<?php echo implode(',', $result['stat2']) ?>];

              chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mi:ss";

              var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
              var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());

              var series = chart.series.push(new am4charts.LineSeries());
              series.dataFields.valueY = "value";
              series.dataFields.dateX = "date";
              series.tooltipText = "{value}";
              series.strokeWidth = 2;
              series.minBulletDistance = 15;

              series.tooltip.background.cornerRadius = 20;
              series.tooltip.background.strokeOpacity = 0;
              series.tooltip.pointerOrientation = "vertical";
              series.tooltip.label.minWidth = 40;
              series.tooltip.label.minHeight = 40;
              series.tooltip.label.textAlign = "middle";
              series.tooltip.label.textValign = "middle";

              var bullet = series.bullets.push(new am4charts.CircleBullet());
              bullet.circle.strokeWidth = 2;
              bullet.circle.radius = 4;
              bullet.circle.fill = am4core.color("#fff");

              var bullethover = bullet.states.create("hover");
              bullethover.properties.scale = 1.3;

              chart.cursor = new am4charts.XYCursor();
              chart.cursor.behavior = "panXY";
              chart.cursor.xAxis = dateAxis;
              chart.cursor.snapToSeries = series;

              chart.events.on("ready", function () {

              });

            });
          </script>
          <div id="chartdiv2" style="height: 200px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>
